#!/usr/bin/env node
require('shelljs/global');

let argv = require('yargs')
  .command('init', '初始化项目', (yargs) => {
    const Init = require('./lib/init.js');
    Init.init();
  })
  .command('add', '新增组件', (yargs) => {
    let argv = yargs.option('n', {
      alias: 'name',
      describe: '组件名称',
      demandOption: true
    })
    .argv;
  })
  .usage('Usage: dyna [options]')
  .example('dyna init --name "project-name"')
  .help('h')
  .alias('h', 'help')
  .alias('v', 'version')
  .argv
